;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        ))
